name: Auto Bot Telegram 24/7

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: 

# FITUR BARU: Mencegah bot nyala ganda yang bikin Crash
concurrency:
  group: bot-telegram
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    # Waktu hidup dinaikkan jadi 6 menit untuk menutupi jeda
    timeout-minutes: 6

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Siapkan Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Library pyTelegramBotAPI
      run: |
        python -m pip install --upgrade pip
        pip install pyTelegramBotAPI

    - name: Nyalakan Mesin Bot!
      run: |
        python bot_keygen.py
